fix ambigous imports
When creating the cloudfunction there was an error:

```
Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Gen1 operation for function projects/nine-testing-250374/locations/europe-west6/functions/blackbox-exporter-k4nun3 failed: Build failed: go: github.com/ninech/blackbox-exporter-cloudfunction/functions.local/app imports
            │ 	github.com/GoogleCloudPlatform/functions-framework-go/funcframework imports
            │ 	cloud.google.com/go/functions/metadata: ambiguous import: found package cloud.google.com/go/functions/metadata in multiple modules:
            │ 	cloud.google.com/go v0.65.0 (/layers/google.go.functions-framework/gopath/pkg/mod/cloud.google.com/go@v0.65.0/functions/metadata)
            │ 	cloud.google.com/go/functions v1.19.3 (/layers/google.go.functions-framework/gopath/pkg/mod/cloud.google.com/go/functions@v1.19.3/metadata); Error ID: 32633c29.
```

When searching for this issue [this github comment](https://github.com/grpc/grpc-go/issues/6696\#issuecomment-1851746892) was found. I then searched for a version `cloud.google.com/go` which is more up2date, but still uses go v1.21. I found [it here](https://github.com/googleapis/google-cloud-go/commit/b9f796e031f7159cdfdb306b380582d2e48c8127). Updating the dependency via:

```
go get cloud.google.com/go@b9f796e031f7159cdfdb306b380582d2e48c8127

go: downloading cloud.google.com/go v0.115.2-0.20240815130937-b9f796e031f7
go: downloading golang.org/x/sync v0.8.0
go: downloading golang.org/x/sys v0.22.0
go: downloading golang.org/x/text v0.16.0
go: downloading github.com/stretchr/testify v1.9.0
go: downloading golang.org/x/net v0.27.0
go: downloading golang.org/x/mod v0.17.0
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/golang/protobuf v1.5.4
go: downloading golang.org/x/oauth2 v0.22.0
go: downloading github.com/google/go-cmp v0.6.0
go: downloading golang.org/x/tools v0.21.1-0.20240508182429-e35e4ccd0d2d
go: downloading google.golang.org/appengine v1.6.8
go: downloading google.golang.org/genproto v0.0.0-20240730163845-b1a4ccb954bf
go: downloading google.golang.org/grpc v1.64.1
go: downloading google.golang.org/protobuf v1.34.2
go: upgraded cloud.google.com/go v0.65.0 => v0.115.2-0.20240815130937-b9f796e031f7
go: upgraded github.com/cespare/xxhash/v2 v2.1.2 => v2.2.0
go: upgraded github.com/golang/protobuf v1.5.2 => v1.5.4
go: upgraded golang.org/x/mod v0.6.0-dev.0.20220419223038-86c51ed26bb4 => v0.17.0
go: upgraded golang.org/x/net v0.2.0 => v0.27.0
go: upgraded golang.org/x/oauth2 v0.0.0-20220909003341-f21342109be1 => v0.22.0
go: upgraded golang.org/x/sys v0.2.0 => v0.22.0
go: upgraded golang.org/x/text v0.4.0 => v0.16.0
go: upgraded golang.org/x/tools v0.1.12 => v0.21.1-0.20240508182429-e35e4ccd0d2d
go: upgraded google.golang.org/appengine v1.6.7 => v1.6.8
go: upgraded google.golang.org/genproto v0.0.0-20200825200019-8632dd797987 => v0.0.0-20240730163845-b1a4ccb954bf
go: upgraded google.golang.org/grpc v1.51.0 => v1.64.1
go: upgraded google.golang.org/protobuf v1.28.1 => v1.34.2
```

should hopefully resolve the error.